---
- defaults:
    shell:
      stdout: true

- shell:
    -
      command: "test -d ~/.config/base16-shell || git clone https://github.com/chriskempson/base16-shell.git ~/.config/base16-shell"
      description: Installing base16 colorschemes
    -
      command: |

        curl https://raw.githubusercontent.com/chriskempson/base16-xresources/master/base16-tomorrow.dark.xresources > ~/.Xresources
        xrdb -load ~/.Xresources
      description: X11 Base16 Colors (set colorscheme for X11 applications; only need to run this once)
